# Generated by Django 6.0 on 2025-12-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_address_options_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(verbose_name='وصف مختصر')),
                ('icon', models.CharField(help_text='مثال: fa-solid fa-building', max_length=100, verbose_name='أيقونة (FontAwesome)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['order'],
            },
        ),
    ]
